services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: notesdb
      POSTGRES_USER: notesuser
      POSTGRES_PASSWORD: notessecret
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - my-connection

  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_NAME: notesdb
      DB_USER: notesuser
      DB_PASSWORD: notessecret
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - my-connection

  frontend:
    build: ./frontend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/html:/usr/share/nginx/html
      - ./frontend/conf.d/:/etc/nginx/conf.d/ 
    depends_on:
      - backend
    networks:
      - my-connection

  
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    networks:
      - my-connection

volumes:
  db_data:

networks:
  my-connection:
    driver: bridge
